[2025-04-06T11:23:45.208+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T11:23:45.220+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.load_data_to_postgres manual__2025-04-06T11:23:38.337814+00:00 [queued]>
[2025-04-06T11:23:45.226+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.load_data_to_postgres manual__2025-04-06T11:23:38.337814+00:00 [queued]>
[2025-04-06T11:23:45.226+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-06T11:23:45.237+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2025-04-06 11:23:38.337814+00:00
[2025-04-06T11:23:45.248+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=219179) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-06T11:23:45.249+0000] {standard_task_runner.py:72} INFO - Started process 219200 to run task
[2025-04-06T11:23:45.248+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'load_data_to_postgres', 'manual__2025-04-06T11:23:38.337814+00:00', '--job-id', '733', '--raw', '--subdir', 'DAGS_FOLDER/weatherAPIDAG.py', '--cfg-path', '/tmp/tmpqzvqnvib']
[2025-04-06T11:23:45.250+0000] {standard_task_runner.py:105} INFO - Job 733: Subtask load_data_to_postgres
[2025-04-06T11:23:45.284+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_api_dag.load_data_to_postgres manual__2025-04-06T11:23:38.337814+00:00 [running]> on host ab13fcc6a433
[2025-04-06T11:23:45.348+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T11:23:38.337814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T11:23:38.337814+00:00'
[2025-04-06T11:23:45.349+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T11:23:45.349+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T11:23:45.350+0000] {logging_mixin.py:190} INFO - Current task name:load_data_to_postgres state:running start_date:2025-04-06 11:23:45.220363+00:00
[2025-04-06T11:23:45.350+0000] {logging_mixin.py:190} INFO - Dag name:weather_api_dag and current dag run status:running
[2025-04-06T11:23:45.351+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-06T11:23:45.357+0000] {base.py:84} INFO - Retrieving connection 'weather_***_conn'
[2025-04-06T11:23:45.365+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-06T11:23:45.373+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-06T11:23:45.373+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=load_data_to_***, run_id=manual__2025-04-06T11:23:38.337814+00:00, execution_date=20250406T112338, start_date=20250406T112345, end_date=20250406T112345
[2025-04-06T11:23:45.380+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-06T11:23:45.380+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-06T11:23:45.381+0000] {logging_mixin.py:190} INFO - Dag name:weather_api_dag queued_at:2025-04-06 11:23:38.345412+00:00
[2025-04-06T11:23:45.381+0000] {logging_mixin.py:190} INFO - Task hostname:ab13fcc6a433 operator:PythonOperator
[2025-04-06T11:23:45.425+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-06T11:23:45.439+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T11:23:45.440+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
